services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loomi_paint_advisor
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    command: sh -c "npx prisma migrate deploy && node dist/utils/importPaintsFromCSV.js && npm run start"
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/loomi_paint_advisor
    depends_on:
      - db
volumes:
  db_data:
