services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loomi_paint_advisor
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/loomi_paint_advisor
    env_file:
      - ./api-service/.env
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
